version: '3.7'
services:
  trustshop:
    build:
      context: ./trustshop
      dockerfile: Dockerfile
    volumes:
      - ./trustshop:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db_trustshop
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db_trustshop
      DB_PORT: 3306

  db_trustshop:
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: trustshop
      MYSQL_USER: trustshop_user
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - db_data_trustshop:/var/lib/mysql

  phpmyadmin_trustshop:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - db_trustshop
    environment:
      PMA_HOST: db_trustshop # これがMySQLサーバのホスト名と一致する必要があります。

volumes:
  db_data_trustshop:
